### ISSUE TITLE
elm-test hangs

### ISSUE THREAD

**Issue by smucode** [rtfeldman/node-test-runner#219] opened 2017-09-19 09:22 UTC
I'm having issues with elm-test hanging, both on my 2016 Macbook Pro, a Dell XPS 15 and on our CI server.

On my MBP I'm consistently able to reproduce (in a fresh ubuntu vm) by:

1. Installing nvm and node 8
2. Installing elm and elm-test via npm
3. Running `elm-package install` and `elm-test init`
4. Running `elm-test` in a loop

Using this approach it appears to hang after ~25 runs on my MBP. Same results trying something similar on native OSX.

On the Dell XPS 15 the raciness is even worse, hangs about 1 in 4 runs.

I also did try using elm-test directly from master (with the unix-socket changes), and was a lot less racy, but it still hung from time to time.

Downgrading to `elm-test 0.18.7` solved the problem.

Let me know if there is anything else you need. Appreciate the great work!

**Comment by isaacseymour** [comment] 2017-09-19 13:18
I'm experiencing this too, but maybe slightly different:

- very very frequent hangs in CI (using CircleCI v2, tests run inside a docker container)
- yet to see a hang on my Macbook (but I haven't tried much either)

This occurred only when upgrading 0.18.7->0.18.9.

**Comment by leifg** [comment] 2017-09-21 14:11
I can confirm this. I also found out that after downgrading node to `8.2.1` I did not experience this error anymore (see my [comment](https://github.com/rtfeldman/node-test-runner/issues/201#issuecomment-328762394))

**Comment by smucode** [comment] 2017-09-28 10:24
I tried to reproduce on node 8.2.1 and can confirm it does hang after running elm-test in a loop for a minute or two (running the string reverse example test).  It does seem to happen less frequently than before, but that might be to me upgrading to high sierra or some other random factor.

**Comment by giulioungaretti** [comment] 2017-10-04 12:36
Same issue with the following set-up (running the example test from elm-test) :

OS: MacOS high Sierra
NODE: v8.5.0
elm-test 0.18.9

**Comment by 7er** [comment] 2017-10-23 20:48
Same issue here. elm-test always hangs if there is a compile error in one of the test files:
OS: Ubuntu Linux 17.04
NODE: v8.7.0
elm-test: 0.18.6

Reverting to node v7.9.0 removes the problem

**Comment by jasononeil** [comment] 2017-10-30 03:33
We've encountered this problem too, but I'm fairly sure it was solved by this 4ecd1068f31e221104454b85d6c0b2c8b8f9902c (the very first commit after 0.18.9).

Setup to reproduce:

```shell
> cd node-test-runner/
> git checkout 432556e
HEAD is now at 432556e... Bump version to 0.18.9
> node -v
v8.7.0
> node bin/elm-test --version
0.18.9
```

I can reproduce by running this bash snippet, essentially trying to run the simplest test multiple times:

> for i in `seq 1 20`; do echo "RUN ${i} of 20"; node bin/elm-test tests/OnePassing.elm ; done

It might not hang running that test just once, but it will consistently hang at some point during the 20 iterations.

Doing a git bisect, I ended up narrowing the problem down to one of these commits, probably (I can't be 100% sure as the tests didn't run for me on these commits, so I skipped them):

> git bisect good
> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 38d2fa98c1daa548b296be4cb509bceb40f7962c
> d0a9a89bd1bf37057ee0fb0d013d2769d92d24bd
> We cannot bisect more!

But as I said, I couldn't reproduce the issue after 4ecd1068f31e221104454b85d6c0b2c8b8f9902c, so I think using unix pipes instead of process.send() has fixed it.

@rtfeldman any chance of an NPM patch release with at least that one extra commit?

**Comment by rtfeldman** [comment] 2017-11-16 19:32
@jasononeil Thank you for the amazing level of detail! 😻 Published as `0.18.10` - on this version I can't reproduce a hang locally after running it 200 times on `example/` on Node 8.4.0.

@smucode @7er @giulioungaretti @leifg @isaacseymour can you see if upgrading to `elm-test` 0.18.10 fixes it for you?

**Comment by 7er** [comment] 2017-11-16 22:48
@rtfeldman I get an error when trying to upgrade

> $ npm install -g elm-test
/home/syver/.nvm/versions/node/v8.7.0/bin/elm-test -> /home/syver/.nvm/versions/node/v8.7.0/lib/node_modules/elm-test/bin/elm-test

> elm-test@0.18.10 install /home/syver/.nvm/versions/node/v8.7.0/lib/node_modules/elm-test

> node install.js

> Unfortunately, there are no elm-test 0.18.10 binaries available on your operating system and architecture.

This might be related to the build errors on travis and appveyor?

**Comment by rtfeldman** [comment] 2017-11-17 03:52
@7er sorry! Fixed.

**Comment by smucode** [comment] 2017-11-27 12:14
I have not been able to reproduce the problem on high sierra, node v.8.9.1 with elm-test 0.18.10. I'll try it on our CI over the next few days.

**Comment by zwilias** [comment] 2017-12-01 21:39
@smucode is this fixed for you?

**Comment by smucode** [comment] 2017-12-01 22:57
I still see it hang from time to time on our CI, so it seems to be a problem still. I have not been able to reproduce on my laptop, even with quite a lot of testing of different permutations of node versions etc...

**Comment by jasononeil** [comment] 2017-12-02 04:15
I've upgraded our CI to run with elm-test 0.18.10 now. If we have any further issues I'll report back but I'm hopeful the fix has worked 👍 

Thanks @rtfeldman!

**Comment by rtfeldman** [comment] 2017-12-03 21:34
@smucode can you try it with the just-released `0.18.11`? It's conceivable that https://github.com/rtfeldman/node-test-runner/pull/228 could have errored in a way that swallowed an exception and hanged...

**Comment by smucode** [comment] 2017-12-04 11:10
It still hangs on our CI, but I think i've narrowed the problem down a bit. What I'm seeing now is not the same problem I initially reported, but manifests similar. It seems to be related to running elm-test in several packages concurrently using lerna. Our project is structured with several packages that are independent elm apps with their own tests. When I run the tests in serial on CI I've not been able to reproduce, when I run them in parallel it hangs quite frequently.

I can reproduce using the following setup: https://github.com/smucode/node-test-runner-issue

In this repo, when i run the tests in serial `npx lerna run test --concurrency=1` it all works fine. But when I run the tests in parallel `npx lerna run test  --concurrency=4` I've seen it hang on my MBP a few times. But more often than not it fails with: 

```
{ Error: connect ECONNREFUSED /tmp/elm_test.sock
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/elm_test.sock' }
```

**Comment by zwilias** [comment] 2017-12-04 11:52
Oooh, that makes sense if there are different instances of `elm-test` trying to share a single socket. I honestly hadn't considered the use-case of multiple instances of `elm-test` 💭

**Comment by rtfeldman** [comment] 2017-12-04 16:12
@smucode Can you verify if `npm install -g elm-test@beta` solves it? (It should, based on your comment on the PR, but just want to make sure!)

**Comment by smucode** [comment] 2017-12-04 20:17
Yes, it appears to be solved. I'm unable to reproduce with 0.18.12-beta.

**Comment by rtfeldman** [comment] 2017-12-10 02:48
Great! 0.18.12 is out of beta now, so I'm gonna close this at last.

Huge thanks to @zwilias for the fixes!

**Closed by rtfeldman** 2017-12-10 02:48 UTC

**Comment by giulioungaretti** [comment] 2017-12-20 09:28
Same for me, all solved now!
