### ISSUE TITLE
Elm-test hangs indefinitely 

### ISSUE THREAD

**Issue by smucode** [rtfeldman/node-test-runner#295] opened 2018-10-01 16:07 UTC
Perhaps every 20th build on our CI, elm-test (0.19.0-beta9) hangs. It just stops right after these messages: 

```
elm-test --verbose
Running elm make /builds/<snip path>/FooTest.elm <snip more tests>/builds/<snip path>/BarTest.elm --output /dev/null
Running elm make /builds/<snip path>/elm-stuff/generated-code/elm-explorations/test/src/Test/Generated/Main2122303807.elm --output /builds/<snip path>/elm-stuff/generated-code/elm-explorations/test/elmTestOutput.js
 ```

Aborting and retrying the tests works.

This was not a problem with 0.18 and the previous elm-test version.

We have no more than 100 test cases in 10 files.

**Comment by rtfeldman** [comment] 2018-10-05 21:03
Thanks! I'm assuming this is a duplicate of https://github.com/rtfeldman/node-test-runner/issues/288 but I appreciate having a separate issue - more data is better! 👍

**Comment by rtfeldman** [comment] 2018-10-05 23:36
I think c123c8 introduced this, but I've had no luck isolating why. It only seems to happen on Travis CI, not on local Linux systems. I'm gonna try rewriting that commit incrementally, pushing to Travis whenever I get it to a state where it works locally again, and see if I can isolate the part of that refactor that introduced the problem.

**Comment by bruckner** [comment] 2018-10-11 15:45
I'm hitting this while running locally (not in CI) with elm-test 0.19.0-beta9 on macos 10.14 Mojave with npm 5.4.2.

Fresh install, ran a half dozen times no problem, now hanging every run.  Small test suite with two tests, was running sub-second.

**Comment by rtfeldman** [comment] 2018-10-11 16:19
@brucker would it be possible for you to share the tests in question?

**Closed** 2018-10-11 19:05 UTC
Labels: bug

**Comment by bruckner** [comment] 2018-10-17 15:41
@rtfeldman It was the tests copied below.  I downgraded to beta8 and that worked.  Just upgraded to beta10 and so far so good.
```
suite : Test
suite =
    describe "RelativeTime"
        [ describe "formatTime"
            [ test "Formats midnight correctly" <|
                \_ ->
                    let
                        midnight =
                            millisToPosix 0

                        result =
                            RelativeTime.formatTime utc midnight
                    in
                    Expect.equal "12:00 am" result
            , test "Formats noon correctly" <|
                \_ ->
                    let
                        noon =
                            millisToPosix (12 * 3600 * 1000)

                        result =
                            RelativeTime.formatTime utc noon
                    in
                    Expect.equal "12:00 pm" result
            ]
        ]
```
