### ISSUE TITLE
Add integrated glob support or document alternatives ways to pattern match files

### ISSUE THREAD

**Issue by tgecho** [rtfeldman/node-test-runner#116] opened 2017-04-16 19:03 UTC
Spun out of and paraphrased from the [Alpha announcement thread](https://groups.google.com/forum/#!topic/elm-dev/7mmElgi4QM8):
> Now you no longer write Main.elm. Instead, you pass whatever files you want to test, e.g. elm-test tests/**/*.elm and it runs just those files.

My fairly vanilla MacOS setup is running Bash 3.x, which doesn't have globstar support, so `elm-test tests/**/*.elm` is basically equivalent to `elm-test tests/*/*.elm`.

Options that I can think of:

1. **Document something like `elm-test $(find tests -type f -name "*.elm")`** (:tophat: [Brian](https://groups.google.com/d/msg/elm-dev/7mmElgi4QM8/_RnPAQCRAgAJ))
  Seems to be a bit noisy since it prints all of the found paths even if they don't have `Test` values, but it's a perfectly serviceable workaround.
1. **Handle the globbing in the tool via something like [node-glob](https://github.com/isaacs/node-glob)**
  I have no opinion about this being the best library for the job, it just came up a bunch.
1. **Tell people to upgrade to Bash 4.**
  Might be a bit aggressive...

The good news is that if I leave the path off it finds all of my tests.

**Comment by rtfeldman** [comment] 2017-04-17 03:30
So we're using `node-glob` under the hood as the default if you don't pass a glob yourself.

The problem is that if you pass a glob, it seems the shell expands it before the `elm-test` binary receives it. When I inspect `process.argv` - at least on `macOS` with `zsh` - what I get is a flat list of files. I don't actually have access to the glob the user put in.

If that's the case, then it seems like `#1` (documenting `elm-test $(find tests -type f -name "*.elm")` for users of Bash 3.x) is the default winner because doing the nicer thing is impossible. 😞

**Comment by tgecho** [comment] 2017-04-17 22:13
We could also tell users to quote the glob pattern argument. It turns out a lot cleaner and should be more portable. 

`elm-test '**/*.elm'`

**Comment by rtfeldman** [comment] 2017-04-25 08:02
@tgecho I *think* this is fixed on `master`...please let me know if not!

**Closed** 2017-04-25 08:02 UTC

**Comment by tgecho** [comment] 2017-04-26 01:25
Works for me! 🎉

**Comment by rtfeldman** [comment] 2017-04-26 04:01
@tgecho what if you don't give it the quotes - does it still work? I would expect it to, but who knows? 😄

**Comment by tgecho** [comment] 2017-04-26 13:28
It works, but you're at the mercy of however your shell handles globbing.

**Comment by rtfeldman** [comment] 2017-04-26 14:48
Sure - just want to make sure!
